# 最初のリリースまで自動化は止めておく
#version: 2
#jobs:
#  build:
#    branches:
#      only:
#        - main
#    docker:
#      - image: tenntenn/docker-hugo-firebase:latest
#    steps:
#      - checkout
#        # install git submodules for managing third-party dependencies
#      - run: git submodule sync && git submodule update --init
#      - run:
#          name: Build Hugo Website
#          command: hugo -v
#      - deploy:
#          name: Deploy Website to Firebase Hosting
#          branch: main
#          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project $FIREBASE_PROJECT_ID
